// svelte/src/App.svelte
<script lang="ts">
  import TheHeader from './components/TheHeader.svelte';
  import CounterCTA from './components/CounterCTA.svelte';
  import { Route, Router } from "svelte-navigator";
  import Home from "./views/Home.svelte";
  import About from "./views/Home.svelte";
  import './styles/main.scss';
</script>

<Router>
  <TheHeader>
    <CounterCTA />
  </TheHeader>
  <main>
<!--    <Route component={Home} />-->
    <Route component={About} />
  </main>
</Router>

// react/src/App.tsx
import React from 'react'
import { Route, Routes } from 'react-router-dom'
import Home from './views/Home'
import About from './views/About'
import TheHeader from './components/TheHeader'
import CounterCTA from './components/CounterCTA'

function App() {
    return (
        <>
            <TheHeader>
                <CounterCTA />
            </TheHeader>
            <main>
                <Routes>
                    <Route path="/" element={<Home />} />
                    <Route path="/about" element={<About />} />
                </Routes>
            </main>
        </>
    )
}

export default App
