// solid/src/App.tsx
import { Component, JSX } from 'solid-js'
import TheHeader from './components/TheHeader'
import CounterCTA from './components/CounterCTA'

const App: Component<{children: JSX.Element}> = (props) => {
    return (
        <>
            <TheHeader>
                <CounterCTA />
            </TheHeader>
            <main>
                { props.children }
            </main>
        </>
    )
}

export default App

// react/src/App.tsx
import React from 'react'
import { Route, Routes } from 'react-router-dom'
import Home from './views/Home'
import About from './views/About'
import TheHeader from './components/TheHeader'
import CounterCTA from './components/CounterCTA'

function App() {
    return (
        <>
            <TheHeader>
                <CounterCTA />
            </TheHeader>
            <main>
                <Routes>
                    <Route path="/" element={<Home />} />
                    <Route path="/about" element={<About />} />
                </Routes>
            </main>
        </>
    )
}

export default App
