// react/src/components/BaseTable/BaseTable.tsx
import React from "react";
import { useCounterStore } from "../../store/counter";
import BaseCell from "../BaseCell/BaseCell";

const cols = [...Array(100)];
const rows = [...Array(100)];

function About() {
  const { computed } = useCounterStore();
  return (
    <table>
      <thead>
        <tr>
          {cols.map((n, index) => (
            <th key={index}>{index}</th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((r, rowN) => (
          <tr key={rowN}>
            {cols.map((c, cellN) => (
              <BaseCell
                key={cellN}
                msg={rowN % 3 ? cellN : cellN * computed.doubleCount}
              />
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

export default About;

// vue3/src/components/BaseTable.vue
<template>
  <table>
    <thead>
      <tr>
        <th v-for="(_, index) in cols" :key="index">{{ index }}</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="(_, rowN) in rows" :key="rowN">
        <td v-for="(_, cellN) in cols" :key="`${rowN}${cellN}`">
          {{ rowN % 3 ? cellN : cellN * counterStore.doubleCount }}
        </td>
        <!--        <BaseCell-->
        <!--          v-for="(_, cellN) in cols"-->
        <!--          :key="`${rowN}${cellN}`"-->
        <!--          :msg="rowN % 3 ? cellN : cellN * counterStore.doubleCount"-->
        <!--        />-->
      </tr>
    </tbody>
  </table>
</template>

<script setup lang="ts">
import { useCounterStore } from '@/stores/counter'
import BaseCell from '@/components/BaseCell.vue'

const counterStore = useCounterStore()
const cols = [...Array(100)]
const rows = [...Array(100)]
</script>
