// solid/src/components/CounterCTA/CounterCTA.tsx
import { counter, increment, decrement } from '../../store'

export const CounterCTA = () => {
    return (
        <>
            <button type="button" onClick={decrement}>
                -
            </button>
            <span>{counter.doubleCount}</span>
            <button type="button" onClick={increment}>
                +
            </button>
        </>
    );
}

// vue3/src/components/CounterCTA.vue
<template>
  <button type="button" @click="counterStore.decrement">-</button>
  <span>{{ counterStore.doubleCount }}</span>
  <button type="button" @click="counterStore.increment">+</button>
</template>

<script setup lang="ts">
import { useCounterStore } from '@/stores/counter'

const counterStore = useCounterStore()
</script>
