// react/src/components/CounterCTA/CounterCTA.tsx
import React from 'react'
import { useCounterStore } from '../../store/counter'

function CounterCTA() {
    const { computed, decrement, increment } = useCounterStore()
    return (
        <>
            <button type="button" onClick={decrement}>
                -
            </button>
            <span>{computed.doubleCount}</span>
            <button type="button" onClick={increment}>
                +
            </button>
        </>
    )
}

export default CounterCTA

// vue3/src/components/CounterCTA.vue
<template>
  <button type="button" @click="counterStore.decrement">-</button>
  <span>{{ counterStore.doubleCount }}</span>
  <button type="button" @click="counterStore.increment">+</button>
</template>

<script setup lang="ts">
import { useCounterStore } from '@/stores/counter'

const counterStore = useCounterStore()
</script>
