// solid/src/components/TheHeader/TheHeader.tsx
import { Component, JSX } from 'solid-js'
import { A } from '@solidjs/router'
import './TheHeader.scss'

const TheHeader: Component<{children: JSX.Element}> = (props) => {
    return (
      <header class="header">
          <nav>
              <A href="/">Home</A>
              <A href="/about">About</A>
          </nav>
          <div class="header">
              {props.children}
          </div>
      </header>
    )
}

export default TheHeader

// react/src/components/TheHeader/TheHeader.tsx
import React from 'react'
import { Link } from 'react-router-dom'
import './TheHeader.scss'

function TheHeader({ children }: { children: React.ReactNode }) {
    return (
      <header className="header">
          <nav>
              <Link to="/">Home</Link>
              <Link to="/about">About</Link>
          </nav>
          <div className="header">
              {children}
          </div>
      </header>
    )
}

export default TheHeader
