// react/src/components/BaseTable/BaseTable.tsx
import React from "react";
import { useCounterStore } from "../../store/counter";
import BaseCell from "../BaseCell/BaseCell";

const cols = [...Array(100)];
const rows = [...Array(100)];

function About() {
  const { computed } = useCounterStore();
  return (
    <table>
      <thead>
        <tr>
          {cols.map((n, index) => (
            <th key={index}>{index}</th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((r, rowN) => (
          <tr key={rowN}>
            {cols.map((c, cellN) => (
              <BaseCell
                key={cellN}
                msg={rowN % 3 ? cellN : cellN * computed.doubleCount}
              />
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

export default About;

// solid/src/components/BaseTable/BaseTable.tsx
import { Index } from 'solid-js'
import { counter } from '../../store'
import BaseCell from '../BaseCell'

const cols = [...Array(100)]
const rows = [...Array(100)]

function About() {
    return (
        <>
            <p>{counter.doubleCount}</p>
            <table>
                <thead>
                    <tr>
                        <Index each={cols}>
                            {(_, index) => <th>{index}</th>}
                        </Index>
                    </tr>
                </thead>
                <tbody>
                    <Index each={rows}>
                        {(_, rowN) => (
                            <tr>
                                <Index each={cols}>
                                    {(_, cellN) => (
                                        <BaseCell
                                            msg={
                                                rowN % 3
                                                    ? cellN
                                                    : cellN *
                                                      counter.doubleCount
                                            }
                                        />
                                    )}
                                </Index>
                            </tr>
                        )}
                    </Index>
                </tbody>
            </table>
        </>
    )
}

export default About
