// solid/src/components/BaseTable/BaseTable.tsx
import { Index } from 'solid-js'
import { counter } from '../../store'
import BaseCell from '../BaseCell'

const cols = [...Array(100)]
const rows = [...Array(100)]

function BaseTable() {
    return (
        <table>
            <thead>
                <tr>
                    <Index each={cols}>{(_, index) => <th>{index}</th>}</Index>
                </tr>
            </thead>
            <tbody>
                <Index each={rows}>
                    {(_, rowN) => (
                        <tr>
                            <Index each={cols}>
                                {(_, cellN) => (
                                    // <BaseCell
                                    //     msg={
                                    //         rowN % 3
                                    //             ? cellN
                                    //             : cellN * counter.doubleCount
                                    //     }
                                    // />
                                    <td>
                                        {rowN % 3
                                            ? cellN
                                            : cellN * counter.doubleCount}
                                    </td>
                                )}
                            </Index>
                        </tr>
                    )}
                </Index>
            </tbody>
        </table>
    )
}

export default BaseTable

// svelte/src/components/BaseTable.svelte
<script lang="ts" module>
	const cols = [...Array(100)]
	const rows = [...Array(100)]
</script>

<script lang="ts">
import BaseCell from './BaseCell.svelte';
import { doubleCount } from '../store/counter'
</script>

<table>
	<thead>
	<tr>
		{#each cols as _, i (i)}
			<th>{ i }</th>
		{/each}
	</tr>
	</thead>
	<tbody>
		{#each rows as _, rowN (rowN)}
			<tr>
			{#each cols as _, cellN (cellN)}
				<BaseCell
					msg={rowN % 3 ? cellN : cellN * $doubleCount}
				/>
			{/each}
			</tr>
		{/each}
	</tbody>
</table>
