// react/src/components/TheHeader/TheHeader.tsx
import React from 'react'
import { Link } from 'react-router-dom'
import './TheHeader.scss'

function TheHeader({ children }: { children: React.ReactNode }) {
    return (
      <header className="header">
          <nav>
              <Link to="/">Home</Link>
              <Link to="/about">About</Link>
          </nav>
          <div className="header">
              {children}
          </div>
      </header>
    )
}

export default TheHeader

// angular/src/components/the-header/the-header.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router'

@Component({
    selector: 'app-the-header',
    imports: [RouterLink],
    templateUrl: './the-header.component.html',
    styleUrl: './the-header.component.scss',
})
export class TheHeaderComponent {}

<header class="header">
  <nav>
    <a class="button" routerLink="/">Home</a> |
    <a class="button" routerLink="/about">About</a>
  </nav>
  <div class="header">
    <ng-content />
  </div>
</header>
